stages:
  fetch:
    cmd: uv run python src/traffic_scraper.py
    deps:
      - src/traffic_scraper.py
    params:
      - fetch.url
      - fetch.output
    outs:
      - data/traffic.csv:
          persist: true
    always_changed: true

  preprocess:
    cmd: uv run python src/traffic_preprocess.py
    deps:
      - src/traffic_preprocess.py
      - data/traffic.csv
    params:
      - preprocess.input
      - preprocess.output
    outs:
      - data/preprocessed/traffic.csv:
          persist: true

  validate:
    cmd: |
      cd gx && uv run python run_checkpoint.py
    deps:
      - data/preprocessed/
    outs:
      - gx/uncommitted:
          persist: true

  test_data:
    cmd: |
      uv run python src/data_test.py
    deps:
      - data/preprocessed/traffic.csv
      - src/data_test.py
    outs:
      - data/reference/traffic:
          persist: true

  train:
    cmd: |
      uv run python src/model/preprocess.py
      git commit -am "Updated model on `date` with DVC pipeline and GitHub workflows" || true
      git push || true
      dvc push || true
    deps:
      - src/model/preprocess.py
      - data/preprocessed/traffic.csv
      - gx/uncommitted
      - data/reference/traffic
    params:
      - train.random_state
      - train.test_size
      - train.use_time_split
      - train.model_type
    outs:
      - models/:
          persist: true