fetch:
  url: "http://portal.drsc.si/traffic/loclist_si.htm"
  output: "data/traffic.csv"

preprocess:
  input: "data/traffic.csv"
  output: "data/preprocessed/traffic.csv"
  random_state: 42
  target_col: "Stanje"
  timestamp_col: "Čas"
  location_col: "Lokacija"
  direction_col: "Smer"
  road_col: "Cesta"
  fill_missing_timestamps: true
  create_time_diff: true
  time_diff_unit: "minutes"
  location_key_cols:
    - "Lokacija"
    - "Smer"
  remove_location_leakage: true
  create_time_features: true
  no_data_label: "Ni podatka"
  no_data_output: "data/preprocessed/traffic_nodata.csv"
  filter_no_data: true

train:
  random_state: 42
  test_size: 0.2
  use_time_split: true
  model_type: "xgboost"
  mlflow_tracking_uri: "https://dagshub.com/TjanKazar/IIS_proj.mlflow"
  mlflow_experiment: "traffic_xgboost_train"
  xgboost:
    n_estimators: 500
    max_depth: 6
    learning_rate: 0.05
    subsample: 0.8
    colsample_bytree: 0.8
    early_stopping_rounds: 20